
package iti.hadeer.employeeservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0-M2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeCRUDsService", targetNamespace = "http://hadeer.iti/", wsdlLocation = "http://localhost:1919/SOAP-Lab1/ws/EmployeeCruds?wsdl")
public class EmployeeCRUDsService
    extends Service
{

    private final static URL EMPLOYEECRUDSSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEECRUDSSERVICE_EXCEPTION;
    private final static QName EMPLOYEECRUDSSERVICE_QNAME = new QName("http://hadeer.iti/", "EmployeeCRUDsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1919/SOAP-Lab1/ws/EmployeeCruds?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEECRUDSSERVICE_WSDL_LOCATION = url;
        EMPLOYEECRUDSSERVICE_EXCEPTION = e;
    }

    public EmployeeCRUDsService() {
        super(__getWsdlLocation(), EMPLOYEECRUDSSERVICE_QNAME);
    }

    public EmployeeCRUDsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEECRUDSSERVICE_QNAME, features);
    }

    public EmployeeCRUDsService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEECRUDSSERVICE_QNAME);
    }

    public EmployeeCRUDsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEECRUDSSERVICE_QNAME, features);
    }

    public EmployeeCRUDsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeCRUDsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeCRUDs
     */
    @WebEndpoint(name = "EmployeeCRUDsPort")
    public EmployeeCRUDs getEmployeeCRUDsPort() {
        return super.getPort(new QName("http://hadeer.iti/", "EmployeeCRUDsPort"), EmployeeCRUDs.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns EmployeeCRUDs
     */
    @WebEndpoint(name = "EmployeeCRUDsPort")
    public EmployeeCRUDs getEmployeeCRUDsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hadeer.iti/", "EmployeeCRUDsPort"), EmployeeCRUDs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEECRUDSSERVICE_EXCEPTION!= null) {
            throw EMPLOYEECRUDSSERVICE_EXCEPTION;
        }
        return EMPLOYEECRUDSSERVICE_WSDL_LOCATION;
    }

}
