
package iti.hadeer.employeeservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0-M2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeCRUDs", targetNamespace = "http://hadeer.iti/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeCRUDs {


    /**
     * 
     * @param arg0
     * @return
     *     returns iti.hadeer.employeeservices.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addEmployee", targetNamespace = "http://hadeer.iti/", className = "iti.hadeer.employeeservices.AddEmployee")
    @ResponseWrapper(localName = "addEmployeeResponse", targetNamespace = "http://hadeer.iti/", className = "iti.hadeer.employeeservices.AddEmployeeResponse")
    @Action(input = "http://hadeer.iti/EmployeeCRUDs/addEmployeeRequest", output = "http://hadeer.iti/EmployeeCRUDs/addEmployeeResponse")
    public Employee addEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        Employee arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns iti.hadeer.employeeservices.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateEmployee", targetNamespace = "http://hadeer.iti/", className = "iti.hadeer.employeeservices.UpdateEmployee")
    @ResponseWrapper(localName = "updateEmployeeResponse", targetNamespace = "http://hadeer.iti/", className = "iti.hadeer.employeeservices.UpdateEmployeeResponse")
    @Action(input = "http://hadeer.iti/EmployeeCRUDs/updateEmployeeRequest", output = "http://hadeer.iti/EmployeeCRUDs/updateEmployeeResponse")
    public Employee updateEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Employee arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns iti.hadeer.employeeservices.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteEmployee", targetNamespace = "http://hadeer.iti/", className = "iti.hadeer.employeeservices.DeleteEmployee")
    @ResponseWrapper(localName = "deleteEmployeeResponse", targetNamespace = "http://hadeer.iti/", className = "iti.hadeer.employeeservices.DeleteEmployeeResponse")
    @Action(input = "http://hadeer.iti/EmployeeCRUDs/deleteEmployeeRequest", output = "http://hadeer.iti/EmployeeCRUDs/deleteEmployeeResponse")
    public Employee deleteEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns iti.hadeer.employeeservices.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployee", targetNamespace = "http://hadeer.iti/", className = "iti.hadeer.employeeservices.GetEmployee")
    @ResponseWrapper(localName = "getEmployeeResponse", targetNamespace = "http://hadeer.iti/", className = "iti.hadeer.employeeservices.GetEmployeeResponse")
    @Action(input = "http://hadeer.iti/EmployeeCRUDs/getEmployeeRequest", output = "http://hadeer.iti/EmployeeCRUDs/getEmployeeResponse")
    public Employee getEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
